language: node_js
node_js:
  - '9.2'
  - '8.0'

script:
  - npm run test

after_success:
  - npm run coveralls

notifications:
  email:
    recipients:
      - ajarombek95@gmail.com
    on_success: always
    on_failure: always