language: node_js
node_js:
  - '9.2'
  - '8.0'

services:
  - mongodb

# Put some mock data into MongoDB for testing purposes
# https://docs.travis-ci.com/user/database-setup/#MongoDB
before_script:
  - mongo meowcat --eval 'db.user.insert({_id: '5a9616e6c5631b2e8bd0bd5e',username: "andy",first: "Andrew",last: "Jarombek",password: "pw",postCount: 4});'

script:
  - npm run test

after_success:
  - npm run coveralls

notifications:
  email:
    recipients:
      - ajarombek95@gmail.com
    on_success: always
    on_failure: always